/* Converts the desktop app's bundled chart data (TypeScript modules in
 * ../poker/src/data) into Dart constants under lib/data/*.g.dart.
 *
 *   node --experimental-transform-types tool/convert_charts.mts [path-to-poker-repo]
 *
 * The desktop repo is the single source of truth for charts; never edit the
 * generated Dart by hand. Frequencies are emitted as doubles. */
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(process.argv[2] ?? "../poker");
const { PREFLOP_BY_DEPTH } = await import(resolve(root, "src/data/preflop.ts"));
const { PUSHFOLD_STACKS, NASH_SHOVE, NASH_CALL } = await import(resolve(root, "src/data/pushfold.ts"));
const { ICM_SCENARIOS } = await import(resolve(root, "src/data/icmPushfold.ts"));

const HEADER = `// GENERATED by tool/convert_charts.mts from the desktop repo's src/data — DO NOT EDIT.\n// Regenerate: node --experimental-transform-types tool/convert_charts.mts ../poker\n\n`;

const dstr = (s: string) => `'${s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\$/g, "\\$")}'`;
const dnum = (n: number) => (Number.isInteger(n) ? `${n}.0` : String(n));
const freqs = (m: Record<string, number>) =>
  `{${Object.entries(m).map(([k, v]) => `${dstr(k)}: ${dnum(v)}`).join(", ")}}`;

/* ---- preflop ---- */
{
  let out = HEADER;
  out += `/// 100bb 6-max opening (RFI) frequencies by position, then hand label.\n`;
  out += `const Map<String, Map<String, double>> kRfi100 = {\n`;
  for (const [pos, chart] of Object.entries(PREFLOP_BY_DEPTH[100].rfi)) out += `  ${dstr(pos)}: ${freqs(chart as Record<string, number>)},\n`;
  out += `};\n\n`;
  out += `/// 100bb defend-vs-open frequencies keyed 'HERO_vs_RAISER', then 'threebet' | 'call', then hand label.\n`;
  out += `const Map<String, Map<String, Map<String, double>>> kVsRfi100 = {\n`;
  for (const [k, v] of Object.entries(PREFLOP_BY_DEPTH[100].vsRfi) as [string, { threebet: Record<string, number>; call: Record<string, number> }][]) {
    out += `  ${dstr(k)}: {'threebet': ${freqs(v.threebet)}, 'call': ${freqs(v.call)}},\n`;
  }
  out += `};\n`;
  writeFileSync("lib/data/preflop_charts.g.dart", out);
}

/* ---- push/fold ---- */
{
  let out = HEADER;
  out += `/// Effective stacks (bb) the Nash push/fold tables are solved for.\n`;
  out += `const List<int> kPushFoldStacks = [${(PUSHFOLD_STACKS as readonly number[]).join(", ")}];\n\n`;
  out += `/// Nash shove frequencies: stack (bb) -> position -> hand label -> 0..1.\n`;
  out += `const Map<int, Map<String, Map<String, double>>> kNashShove = {\n`;
  for (const [stack, byPos] of Object.entries(NASH_SHOVE)) {
    out += `  ${stack}: {\n`;
    for (const [pos, chart] of Object.entries(byPos as Record<string, Record<string, number>>)) out += `    ${dstr(pos)}: ${freqs(chart)},\n`;
    out += `  },\n`;
  }
  out += `};\n\n`;
  out += `/// Nash call-a-shove frequencies: stack (bb) -> 'SHOVER>CALLER' -> hand label -> 0..1.\n`;
  out += `const Map<int, Map<String, Map<String, double>>> kNashCall = {\n`;
  for (const [stack, byKey] of Object.entries(NASH_CALL)) {
    out += `  ${stack}: {\n`;
    for (const [k, chart] of Object.entries(byKey as Record<string, Record<string, number>>)) out += `    ${dstr(k)}: ${freqs(chart)},\n`;
    out += `  },\n`;
  }
  out += `};\n`;
  writeFileSync("lib/data/pushfold_tables.g.dart", out);
}

/* ---- ICM ---- */
{
  let out = HEADER;
  out += `/// A 4-handed bubble scenario (payouts 50/30/20) with ICM-solved jam/call frequencies.\n`;
  out += `class IcmScenarioData {\n  final String id;\n  final String name;\n  final String blurb;\n  /// [SB, BB, other, other] stacks in bb.\n  final List<int> stacks;\n  final Map<String, double> jam;\n  final Map<String, double> call;\n  const IcmScenarioData({required this.id, required this.name, required this.blurb, required this.stacks, required this.jam, required this.call});\n}\n\n`;
  out += `const List<IcmScenarioData> kIcmScenarios = [\n`;
  for (const s of ICM_SCENARIOS as any[]) {
    out += `  IcmScenarioData(id: ${dstr(s.id)}, name: ${dstr(s.name)}, blurb: ${dstr(s.blurb)}, stacks: [${s.stacks.join(", ")}], jam: ${freqs(s.jam)}, call: ${freqs(s.call)}),\n`;
  }
  out += `];\n`;
  writeFileSync("lib/data/icm_scenarios.g.dart", out);
}
console.log("wrote lib/data/{preflop_charts,pushfold_tables,icm_scenarios}.g.dart");
